### ISSUE TITLE
RuntimeException: No saved settings

### ISSUE THREAD

**Issue by Rehdzi** [Feodor0090/nmania#21]
![image](https://user-images.githubusercontent.com/48959158/152982448-ff23595f-17c3-4330-b281-b9fc5d53c585.png)

**Comment by Feodor0090** [comment]
That was intentional, as you can see game falls back to default settings and continue to work.

Also, you are using old version. Now there is an early return on the 20th line: https://github.com/Feodor0090/nmania/blob/a04f583350c9e0dbe24360f6c58ba7b30849ead0/src/nmania/Skin.java#L18-L21
